// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'sjisish', kind: "module", path: './sjisish.html', attributes: []},
{name: 'sjisish.SJISString', kind: "structdeclaration", path: './sjisish/SJISString.html', attributes: []},
{name: 'sjisish.SJISString.raw', kind: "variabledeclaration", path: './sjisish/SJISString.raw.html', attributes: []},
{name: 'sjisish.SJISString.toUTF', kind: "functiondeclaration", path: './sjisish/SJISString.toUTF.html', attributes: ["auto", "const"]},
{name: 'sjisish.toSJIS', kind: "functiondeclaration", path: './sjisish/toSJIS.html', attributes: ["auto"]},
{name: 'sjisish.toUTF', kind: "functiondeclaration", path: './sjisish/toUTF.html', attributes: ["auto"]},
];
